---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - backup.arch.anes
  resources:
  - backupjobs
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.arch.anes
  resources:
  - backupjobs/finalizers
  - repositories/finalizers
  verbs:
  - update
- apiGroups:
  - backup.arch.anes
  resources:
  - backupjobs/status
  - repositories/status
  verbs:
  - get
  - patch
  - update
