apiVersion: backup.arch.anes/v1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: repository-sample
spec:
  # TODO(user): Add fields here
