apiVersion: backup.arch.anes/v1
kind: BackupJob
metadata:
  labels:
    app.kubernetes.io/name: workspace
    app.kubernetes.io/managed-by: kustomize
  name: backupjob-sample
spec:
  # TODO(user): Add fields here
