version: "3"

services:
  dind:
    image: docker:dind
    container_name: restic-operator-dind
    privileged: true
    restart: unless-stopped
    environment:
      DOCKER_TLS_CERTDIR: "" # Disable TLS for simplicity
    volumes:
      - dind-storage:/var/lib/docker
    networks:
      - devcontainer-network

  devcontainer:
    image: ghcr.io/arch-anes/dev-container-kubernetes-go:latest
    container_name: restic-operator-devcontainer
    restart: unless-stopped
    volumes:
      - ../:/workspace
    environment:
      DOCKER_HOST: tcp://dind:2375
    depends_on:
      - dind
    networks:
      - devcontainer-network
    tty: true
    stdin_open: true

volumes:
  dind-storage:

networks:
  devcontainer-network:
